// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAALNxjtL2t9jCLw2YwUSFMY5zjpZiGiBQ',
    appId: '1:324270679165:web:6a779ba5d49778e9a7fd14',
    messagingSenderId: '324270679165',
    projectId: 'secondbase-670b5',
    authDomain: 'secondbase-670b5.firebaseapp.com',
    storageBucket: 'secondbase-670b5.firebasestorage.app',
    measurementId: 'G-MVTK2DDRX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32GVb8MA9WawdTToSjaGr5V0OrRYz2Wo',
    appId: '1:324270679165:android:aa6fbd77cb710206a7fd14',
    messagingSenderId: '324270679165',
    projectId: 'secondbase-670b5',
    storageBucket: 'secondbase-670b5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAALNxjtL2t9jCLw2YwUSFMY5zjpZiGiBQ',
    appId: '1:324270679165:web:46a099ea2e07074fa7fd14',
    messagingSenderId: '324270679165',
    projectId: 'secondbase-670b5',
    authDomain: 'secondbase-670b5.firebaseapp.com',
    storageBucket: 'secondbase-670b5.firebasestorage.app',
    measurementId: 'G-JD5V78LM3R',
  );
}
